# Generated by Django 4.2.6 on 2023-10-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sw', 'Software'), ('hw', 'Hardware')], max_length=2)),
                ('name', models.CharField(max_length=200)),
                ('vendor', models.CharField(max_length=200)),
                ('id_str', models.CharField(blank=True, max_length=200, verbose_name='Unique Identifier')),
            ],
        ),
    ]
