# Generated by Django 4.2.6 on 2023-10-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_combination'),
    ]

    operations = [
        migrations.AddField(
            model_name='combination',
            name='name',
            field=models.CharField(default='VLC on Linux', max_length=200),
            preserve_default=False,
        ),
    ]
