# Generated by Django 4.2.6 on 2023-10-19 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
    ]
