# Generated by Django 4.2.6 on 2023-10-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unique_name',
            field=models.CharField(max_length=200),
        ),
    ]
