# Generated by Django 4.2.6 on 2023-10-19 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_name_product_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='unique_name',
            new_name='searchable_name',
        ),
    ]
