# Generated by Django 4.2.6 on 2023-10-19 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_unique_name_product_searchable_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='searchable_name',
            new_name='search_term',
        ),
    ]
