# Generated by Django 4.2.6 on 2023-10-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_searchable_name_product_search_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='search_term',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
